version: '3'

volumes:
  portainer_data: {}

services:

  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000
      - 8000:8000
    restart: always

  django: &django
    container_name: django
    image: quda_local_django
    depends_on:
      - redis
    volumes:
      - .:/app:z
    working_dir: /app
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8001:8001"
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start

  # docs:
  #   container_name: docs
  #   image: quda_local_docs
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./quda:/app/quda:z
  #   ports:
  #     - "7000:7000"
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   working_dir: /docs

  redis:
    container_name: redis
    image: redis:5.0

  # mongo:
  #   container_name: mongo
  #   image: mongo:4.2

  celeryworker:
    <<: *django
    container_name: celeryworker
    image: quda_local_celeryworker
    depends_on:
      - redis
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    container_name: celerybeat
    image: quda_local_celerybeat
    depends_on:
      - redis
      - celeryworker
    ports: []
    command: /start-celerybeat

  # flower:
  #   <<: *django
  #   container_name: flower
  #   image: quda_local_flower
  #   depends_on:
  #     - celeryworker
  #   ports:
  #     - "5555:5555"
  #   command: /start-flower

  quasar:
    container_name: quasar
    image: quda_local_quasar
    depends_on:
      - django
    volumes:
      - ./quasar:/app:z
    env_file:
      - ./.envs/.local/.quasar
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./compose/local/quasar/Dockerfile
    working_dir: /app
    command: npm run serve
    restart: on-failure

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8081:80"
    depends_on:
      - django
      - quasar
    volumes:
      - ./quda/media/:/media/
      - ./quda/staticfiles/:/static/
      - ./nginx/local.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: none
